{
	"id": "CVE-2020-24583",
	"vulnerabilities": [
		{
			"id": "CVE-2020-24583",
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2020-24583"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.10",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "py-django",
							"architectures": [
								"aarch64",
								"armhf",
								"armv7",
								"ppc64le",
								"s390x",
								"x86",
								"x86_64"
							],
							"repositories": [
								"main"
							]
						},
						"affected": {
							"type": "apk",
							"range": [
								{
									"lt": "1.11.29-r1"
								}
							],
							"fixed": [
								"1.11.29-r1"
							]
						}
					}
				]
			}
		}
	],
	"data_source": "alpine-secdb"
}
