{
	"id": "CVE-2022-????? XSA-398",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2022-????? XSA-398",
				"references": [
					{
						"source": "security.alpinelinux.org",
						"url": "https://security.alpinelinux.org/vuln/CVE-2022-????? XSA-398"
					}
				]
			},
			"ecosystems": [
				"alpine:3.14",
				"alpine:3.15"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.14",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "xen",
							"architectures": [
								"aarch64",
								"armhf",
								"armv7",
								"ppc64le",
								"s390x",
								"x86",
								"x86_64"
							],
							"repositories": [
								"main"
							]
						},
						"affected": {
							"type": "apk",
							"range": [
								{
									"lt": "4.15.2-r2"
								}
							],
							"fixed": [
								"4.15.2-r2"
							]
						}
					}
				]
			}
		},
		{
			"ecosystem": "alpine:3.15",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "xen",
							"architectures": [
								"aarch64",
								"armhf",
								"armv7",
								"ppc64le",
								"s390x",
								"x86",
								"x86_64"
							],
							"repositories": [
								"main"
							]
						},
						"affected": {
							"type": "apk",
							"range": [
								{
									"lt": "4.15.2-r2"
								}
							],
							"fixed": [
								"4.15.2-r2"
							]
						}
					}
				]
			}
		}
	],
	"data_source": {
		"id": "alpine-secdb",
		"raws": [
			"vuls-data-raw-alpine-secdb/3.14/main.json",
			"vuls-data-raw-alpine-secdb/3.15/main.json"
		]
	}
}
