{
	"id": "CVE-2019-17358",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2019-17358",
				"references": [
					{
						"source": "security.alpinelinux.org",
						"url": "https://security.alpinelinux.org/vuln/CVE-2019-17358"
					}
				]
			},
			"ecosystems": [
				"alpine:3.10",
				"alpine:3.11"
			]
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:3.10",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "cacti",
							"architectures": [
								"aarch64",
								"armhf",
								"armv7",
								"ppc64le",
								"s390x",
								"x86",
								"x86_64"
							],
							"repositories": [
								"community"
							]
						},
						"affected": {
							"type": "apk",
							"range": [
								{
									"lt": "1.2.8-r0"
								}
							],
							"fixed": [
								"1.2.8-r0"
							]
						}
					}
				]
			}
		},
		{
			"ecosystem": "alpine:3.11",
			"criteria": {
				"operator": "OR",
				"criterions": [
					{
						"vulnerable": true,
						"package": {
							"name": "cacti",
							"architectures": [
								"aarch64",
								"armhf",
								"armv7",
								"ppc64le",
								"s390x",
								"x86",
								"x86_64"
							],
							"repositories": [
								"community"
							]
						},
						"affected": {
							"type": "apk",
							"range": [
								{
									"lt": "1.2.8-r0"
								}
							],
							"fixed": [
								"1.2.8-r0"
							]
						}
					}
				]
			}
		}
	],
	"data_source": {
		"id": "alpine-secdb",
		"raws": [
			"vuls-data-raw-alpine-secdb/3.10/community.json",
			"vuls-data-raw-alpine-secdb/3.11/community.json"
		]
	}
}
