{
	"id": "CVE-2021-27291",
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2021-27291",
				"references": [
					{
						"source": "security.alpinelinux.org",
						"url": "https://security.alpinelinux.org/vuln/CVE-2021-27291"
					}
				]
			},
			"segments": [
				{
					"ecosystem": "alpine:3.11"
				},
				{
					"ecosystem": "alpine:3.12"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "alpine:3.11",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterions": [
							{
								"type": "version",
								"version": {
									"vulnerable": true,
									"fix_status": {
										"class": "fixed"
									},
									"package": {
										"type": "source",
										"source": {
											"name": "py3-pygments",
											"repositories": [
												"main"
											]
										}
									},
									"affected": {
										"type": "apk",
										"range": [
											{
												"lt": "2.5.2-r1"
											}
										],
										"fixed": [
											"2.5.2-r1"
										]
									}
								}
							}
						]
					}
				}
			]
		},
		{
			"ecosystem": "alpine:3.12",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterions": [
							{
								"type": "version",
								"version": {
									"vulnerable": true,
									"fix_status": {
										"class": "fixed"
									},
									"package": {
										"type": "source",
										"source": {
											"name": "py3-pygments",
											"repositories": [
												"main"
											]
										}
									},
									"affected": {
										"type": "apk",
										"range": [
											{
												"lt": "2.6.1-r1"
											}
										],
										"fixed": [
											"2.6.1-r1"
										]
									}
								}
							}
						]
					}
				}
			]
		}
	],
	"data_source": {
		"id": "alpine-secdb",
		"raws": [
			"vuls-data-raw-alpine-secdb/3.11/main.json",
			"vuls-data-raw-alpine-secdb/3.12/main.json"
		]
	}
}
