{
	"id": "CVE-2022-41323",
	"vulnerabilities": [
		{
			"id": "CVE-2022-41323",
			"references": [
				{
					"source": "security.alpinelinux.org",
					"url": "https://security.alpinelinux.org/vuln/CVE-2022-41323"
				}
			]
		}
	],
	"detection": [
		{
			"ecosystem": "alpine:edge",
			"vulnerable": true,
			"package": {
				"name": "py3-django",
				"repositories": [
					"community"
				],
				"architectures": [
					"aarch64",
					"armhf",
					"armv7",
					"ppc64le",
					"riscv64",
					"s390x",
					"x86",
					"x86_64"
				]
			},
			"affected": {
				"type": "apk",
				"range": [
					{
						"lt": "3.2.16-r0"
					}
				],
				"fixed": [
					"3.2.16-r0"
				]
			}
		}
	],
	"data_source": "alpine-secdb"
}
